# .streamlit/secrets.toml

[postgres]
host = "ec2-35-170-85-206.compute-1.amazonaws.com"
port = 5432
dbname = "dcbt0lh9gd4o55"
user = "djmyopoxfiezbi"
password = "95b9b8b93a1fabe0440e3d31ffcb6077f55fd04e0ee6061d0c2c5776adc52f89"